\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{multi}[2020/03/03 Class for multicolsreports]
\LoadClass[letterpaper, 11pt]{article} 

\usepackage{graphics,graphicx}
\usepackage{multicol} 
\usepackage{parskip}
\usepackage{amsmath}
\usepackage{multirow}
\usepackage[utf8]{inputenc}
\usepackage{fancyhdr}
\usepackage[title]{appendix}
\usepackage{wasysym}
\usepackage{url}
\usepackage[table,xcdraw]{xcolor}
\usepackage{float}
\usepackage[font=footnotesize,labelfont=small]{caption}
\captionsetup{width=0.85\linewidth}
\RequirePackage{geometry}
\geometry{margin=2cm}
\setlength{\parskip}{0.2cm}
\setlength{\parindent}{0pt}